# Generated by Django 3.1.4 on 2020-12-19 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 19, 15, 54, 38, 448059, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 19, 15, 54, 38, 448059, tzinfo=utc)),
        ),
    ]
