# Generated by Django 3.1.4 on 2020-12-06 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 39, 53, 660748, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 12, 6, 11, 39, 53, 660748, tzinfo=utc))),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question')),
            ],
        ),
    ]
