# Generated by Django 3.1.4 on 2020-12-06 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 15, 35, 7, 675590, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 15, 35, 7, 675590, tzinfo=utc)),
        ),
    ]
