# Generated by Django 3.1.4 on 2020-12-06 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20201206_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 15, 40, 26, 462954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 15, 40, 26, 462954, tzinfo=utc)),
        ),
    ]
