# Generated by Django 3.1.4 on 2020-12-06 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20201206_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 17, 31, 57, 772112, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 17, 31, 57, 772112, tzinfo=utc)),
        ),
    ]
